# Generated by Django 4.1.7 on 2023-03-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0171_devicetype_add_bridge'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['component_type', 'component_id'], name='dcim_invent_compone_0560bb_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitemtemplate',
            index=models.Index(fields=['component_type', 'component_id'], name='dcim_invent_compone_77b5f8_idx'),
        ),
    ]
