# Generated by Django 4.2.5 on 2023-10-31 14:37

from django.db import migrations, models
import django.db.models.deletion
import extras.utils
import taggit.managers
import utilities.json


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('extras', '0098_webhook_custom_field_data_webhook_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                (
                    'custom_field_data',
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ('name', models.CharField(max_length=150, unique=True)),
                ('type_create', models.BooleanField(default=False)),
                ('type_update', models.BooleanField(default=False)),
                ('type_delete', models.BooleanField(default=False)),
                ('type_job_start', models.BooleanField(default=False)),
                ('type_job_end', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('conditions', models.JSONField(blank=True, null=True)),
                ('event_type', models.CharField(default='webhook', max_length=30)),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    'content_types',
                    models.ManyToManyField(
                        limit_choices_to=extras.utils.FeatureQuery('eventrules'),
                        related_name='eventrules',
                        to='contenttypes.contenttype',
                    ),
                ),
                (
                    'object_type',
                    models.ForeignKey(
                        limit_choices_to=models.Q(('app_label', 'extras'), ('model__in', ('webhook', 'script'))),
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='eventrule_actions',
                        to='contenttypes.contenttype',
                    ),
                ),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'eventrule',
                'verbose_name_plural': 'eventrules',
                'ordering': ('name',),
            },
        ),
    ]
