# Generated by Django 4.1.8 on 2023-05-18 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('wireless', '0008_wirelesslan_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wirelesslangroup',
            name='level',
        ),
        migrations.RemoveField(
            model_name='wirelesslangroup',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='wirelesslangroup',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='wirelesslangroup',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='wirelesslangroup',
            name='parent',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='children',
                to='wireless.wirelesslangroup',
            ),
        ),
        migrations.AlterModelOptions(
            name='wirelesslangroup',
            options={'ordering': ('name',), 'verbose_name': 'Wireless LAN Group'},
        ),
    ]
