# Generated by Django 4.1.8 on 2023-05-18 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('tenancy', '0010_tenant_relax_uniqueness'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactgroup',
            name='level',
        ),
        migrations.RemoveField(
            model_name='contactgroup',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='contactgroup',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='contactgroup',
            name='tree_id',
        ),
        migrations.RemoveField(
            model_name='tenantgroup',
            name='level',
        ),
        migrations.RemoveField(
            model_name='tenantgroup',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='tenantgroup',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='tenantgroup',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='contactgroup',
            name='parent',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='children',
                to='tenancy.contactgroup',
            ),
        ),
        migrations.AlterField(
            model_name='tenantgroup',
            name='parent',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='children',
                to='tenancy.tenantgroup',
            ),
        ),
    ]
