# Generated by Django 4.1.7 on 2023-03-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0010_tenant_relax_uniqueness'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contactassignment',
            index=models.Index(fields=['content_type', 'object_id'], name='tenancy_con_content_693ff4_idx'),
        ),
    ]
